## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
random_array = np.random.randint(0, 10, size=20)
print("Original array:", random_array)
condition = (random_array > 3) & (random_array < 8)

random_array[condition] = -random_array[condition]

print("Modified array:", random_array)

Original array: [7 7 3 7 9 1 9 8 3 9 3 2 2 3 2 5 3 4 9 7]
Modified array: [-7 -7  3 -7  9  1  9  8  3  9  3  2  2  3  2 -5  3 -4  9 -7]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
random_array = np.random.randint(0, 100, size=(20, 20))
print("Original array:", random_array)

max_el = random_array.max()
max_el_position = np.nonzero(random_array == max_el)
print("Max element:", max_el, "Max element position: ", max_el_position)

random_array[np.nonzero(random_array == max_el)] = 0

print("Modified array:", random_array)

Original array: [[45 93 39 67 88  6 65 25 72 34  2  1 62 81 10 57 92 89 89 20]
 [91 98 72 19 69  0 69 30 20 98 66 10 50 13 47 80 36 84 26 96]
 [53 39 73 80 30 69  6 11 22 51 33 70 96  4 78 92  4 35 53 53]
 [25 55 66  2 16 16 73 61 76  5 57 61 39 47 94 10  5 77 95 53]
 [31 71 51  9 25 54 93 90 21 28 32 28 16 32 56 34  8 31 68  8]
 [87 64 36 45 36  1 34  3 84 20 46  5 88 85 27 72 24 77 37 56]
 [ 6  9 19 93 46 20 46 21 43  5 29 62 41 83 92 43 31 56 10 59]
 [22 94  6 24 45 75 59 90 21 94 34 78 33 59  3 50 99 54 62 22]
 [29 17 53 23 66 59 66 75 74 42 88 70 88 20 64  8 27 21  8 56]
 [80 29 99 90  0 65 94 71 86 81 73 82 98 25 99 38 62 81 24 69]
 [ 1 19 35 25 67 16 53 89 21 81 40 73 45 25 55 50 51 29 63 17]
 [ 4 56 92 45 81  1 66 73 48 53 38 64 26  0 51 68 10 63 16 42]
 [64 73 81 28 84 17 61 10 30 51 18  5 87 33 86  6  1 41 71 37]
 [30 66 65 75 90 25 50 99 92 16 77 50  6  9 11 56 49 97 77 19]
 [33  7 38 49 71 22 78 70 57 80  4 42 97 69 60 93 10 32 57 52]
 [15 13 12 98 49 18 64 55 23 53 28 74 3

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [20]:
random_array = np.random.randint(0, 10, size=(3, 3))
print("Original array:", random_array)



Original array: [[0 9 9]
 [1 1 7]
 [0 7 1]]
Mesh array:  (array([[[0, 0, 0],
        [9, 9, 9],
        [9, 9, 9]],

       [[0, 0, 0],
        [9, 9, 9],
        [9, 9, 9]],

       [[0, 0, 0],
        [9, 9, 9],
        [9, 9, 9]]]), array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]]), array([[[0, 7, 1],
        [0, 7, 1],
        [0, 7, 1]],

       [[0, 7, 1],
        [0, 7, 1],
        [0, 7, 1]],

       [[0, 7, 1],
        [0, 7, 1],
        [0, 7, 1]]]))


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = np.random.randint(0, 10, size=(8, 3))
B = np.random.randint(0, 10, size=(2, 2))

result_rows = []

print(A)
print()
print(B)




[[5 4 1]
 [7 7 6]
 [7 6 6]
 [8 1 0]
 [0 3 7]
 [5 5 2]
 [8 0 7]
 [2 6 1]]

[[7 9]
 [6 3]]


In [19]:
matches = (A[:, np.newaxis, :, np.newaxis] == B[np.newaxis, :, np.newaxis, :])

final_mask = matches.any(axis=(2, 3)).all(axis=1)

print(A[final_mask])

[[7 7 6]
 [7 6 6]
 [0 3 7]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [8]:
# your code

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [9]:
# your code

______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [10]:
# your code

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [11]:
# your code

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [12]:
# your code

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [13]:
# your code

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [14]:
# your code

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [15]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [16]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

FileNotFoundError: ./data/cereal.csv not found.

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
# your code